Repository nghttp2/nghttp2, pull requests merged in 2020-12, with the labels that each got.

#1542 nghttpx: Choose ECDSA cert if compatible signature algorithm available
  src/shrpx_tls.cc
Labels: nghttpx

#1540 Added new nghttp2_ksl.c to Windows makefile
  lib/Makefile.msvc
Labels: build, windows

#1544 nghttpx: Make sure that Pool gets cleared when all buffers are returned
  src/memchunk.h
  src/shrpx_worker.cc
Labels: bug, nghttpx

#1547 Sphinx v3.3
  doc/_exts/sphinxcontrib/rubydomain.py
  doc/mkapiref.py
  lib/includes/nghttp2/nghttp2.h
Labels: build, documentation

#1548 Py3 bindings
  .github/workflows/build.yml
  README.rst
  configure.ac
  doc/sources/python-apiref.rst
  m4/ax_python_devel.m4
  python/Makefile.am
  python/hpackcheck.py
  python/hpackmake.py
  python/nghttp2.pyx
Labels: python
