Repository nghttp2/nghttp2, pull requests merged in 2023-10, with the labels that each got.

#1957 Apps fix
  src/HttpServer.cc
  src/shrpx_connection.cc
Labels: app/nghttpx, app/nghttpd

#1958 nghttpx: Fix bug that --single-process does not work
  src/shrpx.cc
Labels: bug, app/nghttpx

#1963 Fix build error when both clock_gettime and GetTickCount64 are available
  lib/nghttp2_time.c
Labels: area/lib

#1964 nghttpx: Shutdown h3 stream write if reset by a remote endpoint
  src/shrpx_http3_upstream.cc
  src/shrpx_http3_upstream.h
Labels: app/nghttpx, area/quic

#1967 cmake: speed up warning option detection
  CMakeLists.txt
  Makefile.am
  cmake/PickyWarningsC.cmake
  cmake/PickyWarningsCXX.cmake
Labels: build/cmake, area/build

#1969 Update doc
  README.rst
  doc/sources/security.rst
Labels: area/documentation

#1970 Bump ngtcp2
  .github/workflows/build.yml
  README.rst
  configure.ac
  docker/Dockerfile
  src/shrpx.cc
Labels: area/quic, dep/ngtcp2

#1975 Refactor character comparison
  src/util.cc
Labels: area/app

#1973 nghttpx: Stricter transfer-encoding checks
  integration-tests/nghttpx_http1_test.go
  src/http2.cc
  src/http2.h
  src/http2_test.cc
  src/http2_test.h
  src/shrpx-unittest.cc
  src/shrpx_downstream.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
Labels: app/nghttpx, area/app

#1978 Configure cygwin
  configure.ac
  tests/Makefile.am
Labels: platform/windows, area/build

#1977 Prefer clock_gettime if __CYGWIN__ defined
  lib/nghttp2_time.c
Labels: area/lib, platform/windows, area/build

#1986 Bump clang to 15
  .github/workflows/build.yml
Labels: area/github

#1988 Bump quictls to 3.1.4+quic
  .github/workflows/build.yml
Labels: area/github
