Repository nghttp2/nghttp2, pull requests merged in 2024-04, with the labels that each got.

#2132 nghttpx: Migrate to ares_getaddrinfo
  src/shrpx_dns_resolver.cc
  src/shrpx_dns_resolver.h
Labels: app/nghttpx, area/app

#2133 nghttpx: Fix error message
  src/shrpx_dns_resolver.cc
Labels: app/nghttpx, area/app

#2136 nghttpx: Fix QUIC stateless reset stack buffer overflow
  src/shrpx_quic_connection_handler.cc
Labels: app/nghttpx, area/quic, area/app

#2138 Require C++20 compiler
  .github/workflows/build.yml
  CMakeLists.txt
  README.rst
  configure.ac
  src/shrpx_config.h
  src/shrpx_connection_handler.cc
  src/shrpx_log.h
  src/shrpx_tls.cc
  src/shrpx_tls.h
  src/shrpx_worker.cc
  src/shrpx_worker.h
  src/template.h
Labels: area/app

#2140 ci: Bump macos to 13
  .github/workflows/build.yml
  README.rst
Labels: area/github

#2141 Adopt std::to_array and remove make_array
  src/HttpServer.cc
  src/h2load.cc
  src/nghttp.cc
  src/shrpx_client_handler.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_quic_connection_handler.cc
  src/shrpx_router_test.cc
  src/shrpx_signal.cc
  src/shrpx_tls.cc
  src/template.h
  src/util_test.cc
Labels: area/app

#2142 nghttpx: Define APIEndpoints separately
  src/shrpx_api_downstream_connection.cc
Labels: app/nghttpx, area/app

#2144 nghttpx: Do not send error/status body when method is HEAD
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_https_upstream.cc
Labels: app/nghttpx, area/app

#2146 nghttpx: Fix alignment issues in BlockAllocator
  src/allocator.h
Labels: app/nghttpx, area/app

#2149 nghttpx: Simplify parameter declaration for ipc_fd functions
  src/shrpx.cc
Labels: app/nghttpx, area/app

#2150 CMakListsts: Add Build Test info on summary
  CMakeLists.txt
Labels: build/cmake, area/build

#2151 nghttpx: Add extent to ipc_fd explicitly
  src/shrpx.cc
Labels: app/nghttpx, area/app

#2152 src: Add util::format_hex overload functions taking std::span
  src/app_helper.cc
  src/shrpx.cc
  src/shrpx_connection.cc
  src/shrpx_http.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_log_config.cc
  src/shrpx_mruby_module_env.cc
  src/shrpx_quic_connection_handler.cc
  src/shrpx_tls.cc
  src/template.h
  src/template_test.cc
  src/template_test.h
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2154 Make util::decode_hex return std::span
  src/shrpx_config.cc
  src/template.h
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2155 Rewrite util::parse_uint
  src/deflatehd.cc
  src/h2load.cc
  src/nghttp.cc
  src/nghttpd.cc
  src/shrpx.cc
  src/shrpx_config.cc
  src/shrpx_downstream.cc
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/template.h
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2156 Let base64::decode return std::span
  src/base64.h
  src/base64_test.cc
  src/shrpx_http2_upstream.cc
Labels: area/app

#2157 Refactor StringRef
  src/http2.cc
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_downstream.cc
  src/shrpx_http.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/shrpx_log.cc
  src/shrpx_log_config.cc
  src/shrpx_tls.cc
  src/shrpx_worker.cc
  src/template.h
  src/util.cc
  src/util.h
Labels: area/app

#2158 Stringref refactor c str and str
  src/HtmlParser.cc
  src/HttpServer.cc
  src/h2load.cc
  src/http2.cc
  src/http2.h
  src/http2_test.cc
  src/http3.cc
  src/http3.h
  src/memchunk.h
  src/nghttp.cc
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_config.cc
  src/shrpx_config_test.cc
  src/shrpx_connection_handler.cc
  src/shrpx_dns_resolver.cc
  src/shrpx_downstream.cc
  src/shrpx_downstream_test.cc
  src/shrpx_http2_session.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_http_test.cc
  src/shrpx_https_upstream.cc
  src/shrpx_live_check.cc
  src/shrpx_log.cc
  src/shrpx_memcached_connection.cc
  src/shrpx_mruby.cc
  src/shrpx_mruby_module.cc
  src/shrpx_mruby_module_env.cc
  src/shrpx_mruby_module_request.cc
  src/shrpx_router.cc
  src/shrpx_tls.cc
  src/shrpx_worker.cc
  src/shrpx_worker_process.cc
  src/template.h
  src/template_test.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2159 Add StringRef literal operator and remove StringRef::from_lit
  src/HtmlParser.cc
  src/HttpServer.cc
  src/h2load.cc
  src/http2.cc
  src/http2_test.cc
  src/nghttp.cc
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_config_test.cc
  src/shrpx_downstream.cc
  src/shrpx_downstream_test.cc
  src/shrpx_health_monitor_downstream_connection.cc
  src/shrpx_http.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_http_test.cc
  src/shrpx_https_upstream.cc
  src/shrpx_live_check.cc
  src/shrpx_log.cc
  src/shrpx_log.h
  src/shrpx_mruby_module_response.cc
  src/shrpx_router_test.cc
  src/shrpx_tls.cc
  src/shrpx_tls_test.cc
  src/shrpx_worker.cc
  src/shrpx_worker_test.cc
  src/template.h
  src/template_test.cc
  src/tls.h
  src/util.h
  src/util_test.cc
Labels: area/app

#2160 Make StringRef(const std::string&) implicit
  src/template.h
Labels: area/app

#2163 Remove std::string conversion operator from StringRef
  src/HttpServer.cc
  src/http2.cc
  src/nghttp.cc
  src/template.h
Labels: area/app

#2164 Optimize StringRef comparisons against c-string
  src/nghttp.cc
  src/shrpx.cc
  src/shrpx_downstream.cc
  src/shrpx_http.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_https_upstream.cc
  src/template.h
Labels: area/app

#2167 Pack more quic pkt
  src/h2load_quic.cc
  src/shrpx_http3_upstream.cc
Labels: area/app

#2168 nghttpx: Dynamic GSO failover
  src/shrpx_http3_upstream.cc
  src/shrpx_http3_upstream.h
  src/shrpx_quic.cc
  src/shrpx_quic.h
  src/shrpx_quic_connection_handler.cc
Labels: app/nghttpx, area/quic, area/app

#2169 Refactor ImmutableString
  src/template.h
Labels: area/app

#2170 nghttpx: Refactor QUIC data path
  src/shrpx_client_handler.cc
  src/shrpx_client_handler.h
  src/shrpx_connection_handler.cc
  src/shrpx_connection_handler.h
  src/shrpx_http3_upstream.cc
  src/shrpx_http3_upstream.h
  src/shrpx_quic.cc
  src/shrpx_quic.h
  src/shrpx_quic_connection_handler.cc
  src/shrpx_quic_connection_handler.h
  src/shrpx_quic_listener.cc
  src/shrpx_worker.cc
  src/shrpx_worker.h
  src/shrpx_worker_process.cc
Labels: app/nghttpx, area/quic, area/app

#2171 nghttpx: Fix inherited TCP port comparison
  src/shrpx.cc
Labels: app/nghttpx, area/app

#2172 make_websocket_accept_token: Lesser conversions
  src/http2.cc
Labels: area/app

#2173 Add http3::make_field family functions
  src/http3.cc
  src/http3.h
  src/shrpx_http3_upstream.cc
Labels: area/app

#2174 Remove unnecessary namespace qualifications
  src/http2.cc
Labels: area/app

#2175 Refactor http utils
  gennghttpxfun.py
  gentokenlookup.py
  src/HttpServer.cc
  src/http2.cc
  src/http2.h
  src/http2_test.cc
  src/http3.cc
  src/http3.h
  src/nghttp.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_mruby_module_request.cc
  src/shrpx_mruby_module_response.cc
Labels: area/app

#2176 Refactor streq
  gennghttpxfun.py
  gentokenlookup.py
  src/HtmlParser.cc
  src/HttpServer.cc
  src/h2load.cc
  src/http2.cc
  src/nghttp.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_downstream.cc
  src/shrpx_http.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/shrpx_tls.cc
  src/util.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2177 Remove util::streq and let StringRef operator== deal with it
  src/HttpServer.cc
  src/h2load.cc
  src/nghttp.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_downstream.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_tls.cc
  src/shrpx_worker.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2179 Update the link for the Prefix.pdf document. fix #2178
  lib/nghttp2_hd_huffman.c
Labels: area/documentation

#2180 Rewrite util:shuffle
  src/util.h
Labels: area/app
