Repository nghttp2/nghttp2, pull requests merged in 2024-01, with the labels that each got.

#1996 Have less stuff in config.h
  CMakeLists.txt
  cmakeconfig.h.in
  configure.ac
  lib/nghttp2_time.c
  src/timegm.c
  src/timegm.h
  src/util.cc
Labels: area/lib, build/cmake, area/build, area/app, build/autotools

#2036 Revert "nghttpx: Shutdown h3 stream write if reset by a remote endpoint"
  src/shrpx_http3_upstream.cc
  src/shrpx_http3_upstream.h
Labels: app/nghttpx, area/quic, area/app

#2037 ci: Add aws-lc builds
  .github/workflows/build.yml
Labels: area/github

#2038 Bump go modules
  go.mod
  go.sum
Labels: area/integration-test

#2040 Bump go-nghttp2 and go mod tidy
  go.mod
  go.sum
Labels: area/integration-test

#2041 Bump ngtcp2 to v1.2.0
  .github/workflows/build.yml
  README.rst
  docker/Dockerfile
Labels: area/quic

#2042 src: Avoid copies
  src/h2load.cc
  src/nghttp.cc
  src/shrpx_worker.cc
Labels: area/app

#2044 Speed up git clone
  .github/workflows/build.yml
  docker/Dockerfile
Labels: area/github
