Repository nghttp2/nghttp2, pull requests merged in 2025-05, with the labels that each got.

#2339 nghttpx: Adopt std::span::first
  src/shrpx_http3_upstream.cc
  src/shrpx_quic_connection_handler.cc
  src/shrpx_quic_listener.cc
Labels: app/nghttpx, area/app

#2340 Refactor allocator
  src/allocator.h
Labels: area/app

#2341 http2: Adopt std::ranges
  src/http2.cc
Labels: area/app

#2343 shrpx_http: Adopt std::ranges
  src/shrpx_downstream.cc
  src/shrpx_http.cc
  src/shrpx_http.h
Labels: app/nghttpx, area/app

#2344 nghttpx: Tweak DNS timeout and retry
  src/shrpx.cc
Labels: app/nghttpx, area/app

#2342 Fix CMake existence check for GetTickCount64
  CMakeLists.txt
Labels: build/cmake, platform/windows, area/build

#2345 Nghttpx log ranges
  src/shrpx_log.cc
  src/shrpx_log.h
Labels: app/nghttpx, area/app

#2348 shrpx_http2_downstream_connection: Adopt std::ranges
  src/shrpx_http2_downstream_connection.cc
Labels: app/nghttpx, area/app

#2349 shrpx_http2_upstream: Adopt std::ranges
  src/shrpx_http2_upstream.cc
Labels: app/nghttpx, area/app

#2350 Update README.rst
  README.rst
Labels: area/documentation

#2351 shrpx_http3_upstream: Adopt std::ranges
  src/shrpx_http3_upstream.cc
Labels: app/nghttpx, area/app

#2352 Remove util::copy_lit
  src/util.h
Labels: area/app

#2353 Rewrite starts_with, ends_with and streq with std::ranges
  gentokenlookup.py
  src/http2.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_config.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2355 Do not submit RST_STREAM more than once
  lib/nghttp2_session.c
  lib/nghttp2_session.h
  lib/nghttp2_submit.c
  tests/nghttp2_session_test.c
Labels: area/lib

#2356 nghttpx: Rework frontend address resolution for QUIC packets
  src/shrpx_config.h
  src/shrpx_worker.cc
Labels: app/nghttpx, area/app

#2357 nghttpx: Fix Forwarded By
  src/shrpx_client_handler.cc
  src/shrpx_client_handler.h
  src/shrpx_quic_connection_handler.cc
  src/shrpx_tls.cc
Labels: app/nghttpx, area/app

#2358 shrpx_https_upstream: Adopt std::ranges
  src/memchunk.h
  src/memchunk_test.cc
  src/shrpx_https_upstream.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: app/nghttpx, area/app

#2359 Ranges base64
  src/base64.h
  src/base64_test.cc
  src/http2.cc
  src/nghttp.cc
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http_downstream_connection.cc
Labels: area/app

#2360 StringRef: Piggyback std::hash<std::string_view>
  src/template.h
Labels: area/app

#2361 Nghttpx ranges part1
  src/shrpx_client_handler.cc
  src/shrpx_connection_handler.cc
  src/shrpx_downstream.cc
  src/shrpx_downstream.h
  src/shrpx_downstream_queue.cc
  src/shrpx_http_downstream_connection.cc
Labels: app/nghttpx, area/app

#2362 shrpx_tls: Adopt std::ranges
  src/shrpx_log.cc
  src/shrpx_log.h
  src/shrpx_tls.cc
  src/shrpx_tls.h
  src/template.h
  src/template_test.cc
  src/template_test.h
  src/util.h
Labels: app/nghttpx, area/app

#2366 integration: Disable IPv6 on backend for external DNS tests
  .github/workflows/build.yml
  integration-tests/server_tester.go
Labels: area/integration-test

#2364 Add helper template for StringRef from contiguous range
  src/http2.cc
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_downstream.cc
  src/shrpx_http.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/shrpx_log.cc
  src/shrpx_worker.cc
  src/template.h
  src/template_test.cc
  src/template_test.h
  src/util.cc
  src/util.h
Labels: area/app

#2367 shrpx_worker: Adopt std::ranges
  src/shrpx_worker.cc
Labels: app/nghttpx, area/app

#2370 Single pass header name lowecase
  src/allocator.h
  src/shrpx_downstream.cc
Labels: app/nghttpx, area/app

#2372 Nghttpx ranges part2
  src/shrpx_downstream_connection_pool.cc
  src/shrpx_memcached_connection.cc
  src/shrpx_worker_process.cc
Labels: app/nghttpx, area/app

#2373 Rewrite format_hex
  src/shrpx.cc
  src/shrpx_http.cc
  src/shrpx_log_config.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2374 Nghttpx ranges part3
  src/http3.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_dns_tracker.cc
  src/shrpx_quic.cc
  src/shrpx_quic_connection_handler.cc
  src/shrpx_router.cc
Labels: app/nghttpx, area/app

#2375 shrpx_config: Adopt std::ranges
  src/shrpx_config.cc
Labels: app/nghttpx, area/app

#2378 Nghttpx remove ocsp
  CMakeLists.txt
  Makefile.am
  README.rst
  configure.ac
  doc/bash_completion/nghttpx
  doc/h2load.1
  doc/nghttp.1
  doc/nghttpd.1
  doc/nghttpx.1
  doc/nghttpx.1.rst
  doc/nghttpx.h2r
  script/CMakeLists.txt
  script/Makefile.am
  script/README.rst
  script/fetch-ocsp-response
  src/shrpx.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_connection_handler.cc
  src/shrpx_connection_handler.h
  src/shrpx_tls.cc
  src/shrpx_tls.h
  src/shrpx_tls_test.cc
  src/shrpx_worker_process.cc
Labels: app/nghttpx, area/app

#2380 Nghttpx remove memcached session cache
  README.rst
  doc/bash_completion/nghttpx
  doc/h2load.1
  doc/nghttp.1
  doc/nghttpd.1
  doc/nghttpx.1
  doc/nghttpx.1.rst
  doc/nghttpx.h2r
  doc/sources/nghttpx-howto.rst
  src/memchunk.h
  src/memchunk_test.cc
  src/memchunk_test.h
  src/shrpx.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_connection.cc
  src/shrpx_connection.h
  src/shrpx_connection_handler.cc
  src/shrpx_rate_limit.cc
  src/shrpx_tls.cc
  src/shrpx_worker.cc
  src/shrpx_worker.h
Labels: app/nghttpx, area/app

#2381 shrpx: Adopt std::ranges
  src/shrpx.cc
Labels: app/nghttpx, area/app

#2382 buffer: Adopt std::ranges
  src/buffer.h
Labels: area/app

#2383 memchunk: Adopt std::ranges
  src/memchunk.h
  src/memchunk_test.cc
  src/memchunk_test.h
Labels: area/app

#2384 template: Adopt std::ranges
  src/HtmlParser.cc
  src/HttpServer.cc
  src/allocator.h
  src/base64_test.cc
  src/h2load.cc
  src/nghttp.cc
  src/shrpx_client_handler.cc
  src/shrpx_config.cc
  src/shrpx_connection.cc
  src/shrpx_dns_tracker.cc
  src/shrpx_downstream_queue.cc
  src/shrpx_downstream_test.cc
  src/shrpx_http2_downstream_connection.cc
  src/shrpx_http2_session.cc
  src/shrpx_http2_upstream.cc
  src/shrpx_http3_upstream.cc
  src/shrpx_live_check.cc
  src/shrpx_tls.cc
  src/shrpx_worker.cc
  src/template.h
  src/template_test.cc
  src/util_test.cc
Labels: area/app

#2385 Add ImmutableString string literal
  src/shrpx_worker_test.cc
  src/template.h
  src/template_test.cc
Labels: area/app

#2386 Rewrite percent encoding
  src/shrpx_http.cc
  src/template.h
  src/template_test.cc
  src/util.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2387 Declare hex_to_uint_tbl constinit
  src/util.h
Labels: area/app

#2389 Rewrite util::utos functions
  src/h2load.cc
  src/http2.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/shrpx_log.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2391 Make util::format_hex constexpr
  src/util.h
Labels: area/app

#2392 Remove util::inp_strlower in favor of util::tolower
  src/h2load.cc
  src/http2.cc
  src/http2.h
  src/nghttp.cc
  src/nghttpd.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2393 Refactor util::make_http_hostport and util::make_hostport
  src/shrpx.cc
  src/shrpx_config.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2394 Refine output iterator requirements
  src/base64.h
  src/util.h
Labels: area/app

#2395 Make base64 encoder/decoder constexpr
  src/base64.h
Labels: area/app

#2396 Optimize util::utos
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2398 Optimize util::utox
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2399 Disallow array to substitute R &&
  src/allocator.h
  src/app_helper.cc
  src/base64.h
  src/memchunk.h
  src/shrpx_log.cc
  src/shrpx_log.h
  src/template.h
  src/util.h
Labels: area/app

#2401 Rewrite format_iso8601 with std::chrono
  CMakeLists.txt
  cmakeconfig.h.in
  configure.ac
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2402 Util refactor format date
  src/util.cc
Labels: area/app

#2403 Hide iso8601_date in unnamed namespace
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2404 Rewrite format_iso8601_basic with std::chrono
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2405 Rewrite format_common_log
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2406 Rewrite format_http_date with std::chrono
  src/HttpServer.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2407 Amend date
  src/util.cc
  src/util_test.cc
Labels: area/app

#2408 Generate tables for character predicate functions
  src/util.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2410 Rewrite util::upcase
  src/util.cc
  src/util.h
  src/util_test.cc
  src/util_test.h
Labels: area/app

#2411 Write http status string directly
  src/shrpx_https_upstream.cc
Labels: app/nghttpx, area/app

#2412 Allow Writing data to Memchunks directly
  src/memchunk.h
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
Labels: area/app

#2413 util: Adopt std::ranges
  src/shrpx_worker.cc
  src/util.cc
  src/util.h
Labels: area/app

#2415 Remove Memchunks::append(const char (&)[N])
  src/http2.cc
  src/memchunk.h
  src/memchunk_test.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
Labels: area/app

#2416 Add test for Memchunks::reserve
  src/memchunk_test.cc
  src/memchunk_test.h
Labels: area/app

#2417 Remove draft h2 alpn support
  README.rst
  src/HttpServer.cc
  src/h2load.cc
  src/nghttp.cc
  src/shrpx.cc
  src/shrpx_tls.cc
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: area/app

#2420 Nghttpx ranges part4
  src/buffer_test.cc
  src/shrpx_config.cc
  src/shrpx_config_test.cc
  src/shrpx_http_test.cc
  src/shrpx_worker.h
  src/siphash.cc
  src/siphash_test.cc
  src/util_test.cc
Labels: area/app

#2424 Safer way to write data directly to Memchunks buffer
  src/memchunk.h
  src/memchunk_test.cc
  src/shrpx_http.h
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/util.h
Labels: area/app

#2425 Remove Memchunks::append return value
  src/h2load_http2_session.cc
  src/memchunk.h
Labels: area/app

#2426 nghttp: Adopt std::ranges
  src/nghttp.cc
Labels: app/nghttp, area/app

#2427 nghttpd: Adopt std::ranges
  src/HttpServer.cc
Labels: app/nghttpd, area/app

#2432 nghttpx: Fix logger does not show address correctly
  src/shrpx_log.cc
  src/shrpx_log.h
  src/util.cc
  src/util.h
  src/util_test.cc
Labels: app/nghttpx, area/app

#2439 Remove NGHTTP2_MAX_UINT64_DIGITS
  src/shrpx_https_upstream.cc
  src/shrpx_log.cc
  src/util.h
Labels: app/nghttpx, area/app

#2443 Unordered map
  CMakeLists.txt
  cmakeconfig.h.in
  configure.ac
  src/HttpServer.cc
  src/HttpServer.h
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_dns_tracker.h
  src/shrpx_downstream_queue.cc
  src/shrpx_downstream_queue.h
  src/shrpx_worker.cc
  src/util.cc
  src/util.h
Labels: area/app

#2444 src/template.h: add missing `cstdint` include
  src/template.h
Labels: area/app

#2445 Use std::unordered_set if applicable
  src/HttpServer.cc
  src/app_helper.cc
  src/nghttp.cc
  src/nghttp.h
  src/shrpx.cc
  src/shrpx_api_downstream_connection.cc
  src/shrpx_config.cc
  src/shrpx_config.h
  src/shrpx_downstream_connection_pool.h
  src/shrpx_downstream_queue.h
  src/shrpx_https_upstream.cc
Labels: area/app

#2446 App cleanup
  src/app_helper.h
  src/shrpx_config.h
  src/shrpx_worker.cc
  src/util.cc
Labels: area/app
