Repository nghttp2/nghttp2, pull requests merged in 2025-02, with the labels that each got.

#2304 cmake: Disable src tests if BUILD_TESTING is OFF
  src/CMakeLists.txt
Labels: build/cmake, area/build

#2305 Add QNX Support
  src/util.h
Labels: area/app

#2306 clang-format
  src/util.h
Labels: area/app

#2310 Bump ngtcp2
  .github/workflows/build.yml
  README.rst
  cmake/PickyWarningsCXX.cmake
  configure.ac
  docker/Dockerfile
Labels: area/quic, dep/ngtcp2
