Repository nghttp2/nghttp2, pull requests merged in 2025-06, with the labels that each got.

#2449 Bump llhttp to v9.3.0
  src/h2load_http1_session.cc
  src/nghttp.cc
  src/shrpx_http2_session.cc
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  third-party/llhttp/LICENSE
  third-party/llhttp/README.md
  third-party/llhttp/include/llhttp.h
  third-party/llhttp/src/api.c
  third-party/llhttp/src/llhttp.c
Labels: third-party/llhttp, area/app, area/third-party

#2451 src: Refactor siphash key generation
  src/shrpx_quic.cc
  src/shrpx_quic.h
Labels: app/nghttpx, area/quic, area/app

#2453 Src refactor
  src/http2.cc
  src/http2.h
  src/http2_test.cc
  src/http2_test.h
  src/nghttp.cc
  src/shrpx_downstream.cc
  src/shrpx_downstream.h
  src/shrpx_downstream_test.cc
  src/shrpx_http.cc
  src/shrpx_http.h
  src/shrpx_http_downstream_connection.cc
  src/shrpx_https_upstream.cc
  src/shrpx_mruby_module_env.cc
  src/shrpx_router.cc
  src/shrpx_router.h
  src/tls.cc
  src/tls.h
  src/util.cc
Labels: area/app

#2455 nghttpd: Support SSLKEYLOGFILE
  src/HttpServer.cc
Labels: app/nghttpd, area/app

#2458 nghttpx: Use std::getline to read QUIC secrets
  src/shrpx_config.cc
Labels: app/nghttpx, area/quic, area/app

#2463 Do not trigger android workflow on tag event
  .github/workflows/android.yml
Labels: area/github

#2467 src: Adopt IP_PMTUDISC_PROBE
  src/shrpx_worker.cc
Labels: area/app
